---
title: "GLUE-urbanQuant"
subtitle: "Distance Data"
author: "David Murray-Stoker"
output:
  pdf_document:
    toc: true
    toc_depth: 4
    fig_caption: yes
    latex_engine: xelatex
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(results = "hold", fig.pos = "H", fig.align = "center", out.width = "92.5%")
options(knitr.graphics.error = FALSE)
kableExtra::usepackage_latex("float")
```

```{r Load Packages for R Markdown, include = FALSE}
library(kableExtra)
library(knitr)
```

```{r Load Packages & Data, include = FALSE}
## Load the tidyverse
library(tidyverse)

## Packages for data extraction and management
library(geosphere)
```


\newpage
# Load Data

```{r create_df_list Function, echo = TRUE}
#' Creates list with dataframes as elements for all CSVs in inpath
#' 
#' @param inpath Path to directory containing CSVs to load
#' 
#' @return df_list. List of dataframes, each from a different CSV
create_df_list <- function(inpath){
  
  # Get all csv files in inpath
  files <- dir(inpath, pattern = "*.csv")
  
  # Read in all the files, appending the path before the filename
  df_list <- files %>%
    map(~ read_csv(file.path(inpath, .), show_col_types = FALSE))
  
  return(df_list)
}
```

\vspace{10pt}

```{r Create Lists of Dataframes, echo = TRUE}
## Load all GLUE transects as a list
GLUE.transects.data.path <- "data/data_filtered/"
GLUE.transects.df.list   <- create_df_list(GLUE.transects.data.path)

# Load all random points as a list
random.points.data.path <- "data/filtered_random_points/"
random.points.df.list   <- create_df_list(random.points.data.path)

## Load all systematic points as a list
systematic.points.data.path <- "data/filtered_systematic_points/"
systematic.points.df.list   <- create_df_list(systematic.points.data.path)

## Load all random transects as a list
random.transects.data.path <- "data/filtered_random_transects/"
random.transects.df.list   <- create_df_list(random.transects.data.path)
```

\vspace{10pt}

```{r City Information Data, echo = TRUE}
## Load city information data
city.information.data <- read_csv(
	"data/full_city_information.csv",
	show_col_types = FALSE
	)
```




\newpage
# Distance from the Urban Center

Description goes here...



## Distance Functions

Description goes here...


\newpage
### calculate_GLUE_site_distance

```{r calculate_GLUE_site_distance Function, echo = TRUE}
#' Description goes here...
#' 
#' 

calculate_GLUE_site_distance <- function(df, data_out){
	
  # Get city name
	city <- df %>% pull(City) %>% unique()
	
	# Get country name
	country <- df %>% pull(Country) %>% unique()
	
	# Set the site coordinates
	site.coordinates <- tibble(
		Longitude = df$Population_Longitude,
		Latitude = df$Population_Latitude
		)
	
	# Set coordinates of the city center
	# Longitude
	city.center.longitude <- df$City_Longitude %>% unique()
	# Latitude
	city.center.latitude <- df$City_Latitude %>% unique()
	
	# Calculate distance to the city center for each site
	distance.df <- distGeo(
		p1 = site.coordinates,
		p2 = c(city.center.longitude, city.center.latitude)
		) %>%
		as_tibble() %>%
		mutate(Distance = value/1000)
	
	# Add city to the data
	distance.df$City <- city
	
	# Add country to the data
	distance.df$Country <- country
	
	# Add a unique identifier to the data
	distance.df$UID <- paste(distance.df$City, rownames(distance.df), sep = ".")
	
	# Reorganize the data
	distance.df <- distance.df %>%
		select(UID, Country, City, Distance)
	
	# Set the outpath for the distance data
	outpath <- paste0(data_out, city, "_distance.csv")
	
	# Export the filtered dataframe
	write_csv(distance.df, file = outpath, col_names = TRUE)
	
	}
```




\newpage
### calculate_points_transects_distance

```{r calculate_points_transects_Distance Function, echo = TRUE}
#' Description goes here...
#' 
#' 

calculate_points_transects_distance <- function(df, city_centers, data_out){
	
	# Get city name
	city <- df %>% pull(City) %>% unique()
	
	# Get country name
	country <- df %>% pull(Country) %>% unique()
	
	# Set the site coordinates
	site.coordinates <- tibble(
		Longitude = df$Longitude,
		Latitude = df$Latitude
		)
	
	# Set coordinates of the city center
	# Longitude
	city.center.longitude <- city_centers %>%
		filter(City == city) %>%
		select(City_Longitude) %>%
		unique() %>%
		as.numeric()
	# Latitude
	city.center.latitude <- city_centers %>%
		filter(City == city) %>%
		select(City_Latitude) %>%
		unique() %>%
		as.numeric()
	
	# Calculate distance to the city center for each site
	distance.df <- distGeo(
		p1 = site.coordinates,
		p2 = c(city.center.longitude, city.center.latitude)
		) %>%
		as_tibble() %>%
		mutate(Distance = value/1000)
	
	# Add city to the data
	distance.df$City <- city
	
	# Add country to the data
	distance.df$Country <- country
	
	# Add a unique identifier to the data
	distance.df$UID <- paste(distance.df$City, rownames(distance.df), sep = ".")
	
	# Reorganize the data
	distance.df <- distance.df %>%
		select(UID, Country, City, Distance)
	
	# Set the outpath for the distance data
	outpath <- paste0(data_out, city, "_distance.csv")
	
	# Export the filtered dataframe
	write_csv(distance.df, file = outpath, col_names = TRUE)
	
	}
```




\newpage
### Calculate Distance Data

```{r Calculate Distance Data, echo = TRUE, message = FALSE, error = FALSE, results = "hide"}
## Set outpath for distance data
# GLUE transects
outpath_1 <- "data/distance_data/GLUE_transects_distance/"
# Random points
outpath_2 <- "data/distance_data/random_points_distance/"
# Systematic points
outpath_3 <- "data/distance_data/systematic_points_distance/"
# Random transects
outpath_4 <- "data/distance_data/random_transects_distance/"

## Calculate distance data
# GLUE transects
purrr::walk(
	GLUE.transects.df.list,
	calculate_GLUE_site_distance,
	data_out = outpath_1
	)
# Random points
purrr::walk(
	random.points.df.list,
	calculate_points_transects_distance,
	city_centers = city.information.data,
	data_out = outpath_2
	)
# Systematic points
purrr::walk(
	systematic.points.df.list,
	calculate_points_transects_distance,
	city_centers = city.information.data,
	data_out = outpath_3
	)
# Random transects
purrr::walk(
	random.transects.df.list,
	calculate_points_transects_distance,
	city_centers = city.information.data,
	data_out = outpath_4
	)
```




\newpage
# Workspace Information

```{r R Packages, echo = FALSE}
df_session_packages <- devtools::session_info()$packages %>% 
  as.data.frame(.) %>% 
  dplyr::filter(attached == TRUE) %>% 
  dplyr::select(loadedversion, date) %>% 
  rownames_to_column

colnames(df_session_packages) <- c("Package", "Loaded Version", "Date")

kable(
  df_session_packages, 
  booktabs = TRUE,
  caption = "Packages required for data management and analyses."
  ) %>%
	kable_styling(
		full_width = FALSE,
  	latex_options = c("HOLD_position", "striped")
  	) 
```





