---
title: "GLUE-urbanQuant"
subtitle: "GMIS Data"
author: "David Murray-Stoker"
output:
  pdf_document:
    toc: true
    toc_depth: 4
    fig_caption: yes
    latex_engine: xelatex
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(results = "hold", fig.pos = "H", fig.align = "center", out.width = "92.5%")
options(knitr.graphics.error = FALSE)
kableExtra::usepackage_latex("float")
```

```{r Load Packages for R Markdown, include = FALSE}
library(kableExtra)
library(knitr)
```

```{r Load Packages & Data, include = FALSE}
## Load the tidyverse
library(tidyverse)

## Packages for data extraction and management
library(raster)
```


# Load Data

```{r create_df_list Function, echo = TRUE}
#' Creates list with dataframes as elements for all CSVs in data_in
#' 
#' @param data_in Path to directory containing CSVs to load
#' 
#' @return df_list. List of dataframes, each from a different CSV
create_df_list <- function(data_in){
  
  # Get all csv files in data_in
  files <- dir(data_in, pattern = "*.csv")
  
  # Read in all the files, appending the path before the filename
  df_list <- files %>%
    map(~ read_csv(file.path(data_in, .), show_col_types = FALSE))
  
  return(df_list)
  
  }
```

\vspace{10pt}

```{r Create Lists of Dataframes, echo = TRUE}
## Load all GLUE transects as a list
GLUE.transects.data.path <- "data/data_filtered/"
GLUE.transects.df.list   <- create_df_list(GLUE.transects.data.path)

# Load all random points as a list
random.points.data.path <- "data/filtered_random_points/"
random.points.df.list   <- create_df_list(random.points.data.path)

## Load all systematic points as a list
systematic.points.data.path <- "data/filtered_systematic_points/"
systematic.points.df.list   <- create_df_list(systematic.points.data.path)

## Load all random transects as a list
random.transects.data.path <- "data/filtered_random_transects/"
random.transects.df.list   <- create_df_list(random.transects.data.path)
```




\newpage
# GMIS Data

Description goes here...




## GMIS Functions

Description goes here...




\newpage
### get_country_code

```{r get_country_code Function, echo = TRUE}
#' Description goes here...
#' 
#' 

## Set the function
get_country_code <- function(df){
	
	# Get country
	country <- df %>% pull(Country) %>% unique()
	
  # Convert country to country code
  country_code <- case_when(country == "Argentina" ~ "ARG",
                            country == "Australia" ~ "AUS",
                            country == "Belgium" ~ "BEL",
                            country == "Brazil" ~ "BRA",
                            country == "Canada" ~ "CAN",
                            country == "Chile" ~ "CHL",
                            country == "China" ~ "CHN",
                            country == "Colombia" ~ "COL",
                            country == "Ecuador" ~ "ECU",
                            country == "Finland" ~ "FIN",
                            country == "France" ~ "FRA",
                            country == "Germany" ~ "DEU",
                            country == "Greece" ~ "GRC",
                            country == "Iran" ~ "IRN",
                            country == "Japan" ~ "JPN",
                            country == "Mexico" ~ "MEX",
                            country == "Netherlands" ~ "NLD",
                            country == "Norway" ~ "NOR",
                            country == "New Zealand" ~ "NZL",
                            country == "Poland" ~ "POL",
                            country == "Portugal" ~ "PRT",
                            country == "Sweden" ~ "SWE",
                            country == "Switzerland" ~ "CHE",
                            country == "UK" ~ "GBR",
                            country == "USA" ~ "USA",
                            country == "South Africa" ~ "ZAF",
                            TRUE ~ "NA")
	
	return(country_code)
	
	}
```




\newpage
### load_raster

```{r load_raster Function, echo = TRUE}
#' Description goes here...
#' 
#' 

## Set the function
load_raster <- function(country_code, city, data_in){
	
	# Regex pattern to match country"s raster
	# Handles a few edge cases for countries with multiple rasters
	if(country_code == "USA" & !(city %in% c("Fairbanks", "Anchorage"))){
		pattern <- "^USAw1_.*.tif$"
	}else if(country_code == "USA" & city %in% c("Fairbanks", "Anchorage")){
		pattern <- "^USAW3_.*.tif$"  
	}else if(country_code == "NZL"){
		pattern <- "^NZLe_.*.tif$"  
	}else{
		pattern <- sprintf("^%s_.*.tif$", country_code)      
	}
	
	# Path to raster
	raster_file <- list.files(data_in, pattern = pattern, recursive = TRUE)
	raster_path <- paste0(data_in, raster_file)
	
	# Load and return raster
	raster <- raster::raster(raster_path)
	
	return(raster)
	
	}
```




\newpage
### calculate_GLUE_transect_GMIS

```{r calculate_GLUE_transect_GMIS Function, echo = TRUE}
#' Description goes here...
#' 
#' 

## Set the function
calculate_GLUE_transect_GMIS <- function(df, data_in, data_out, buffer = 250){
	
  # Get city name
	city <- df %>% pull(City) %>% unique()

	# Do not execute if file exists
	data_out <- paste0(data_out, city, "_GMIS.csv")
	if(file.exists(data_out)){
		print(sprintf("GMIS data already exists for %s", city))
		# Otherwise extract data
	}else{
		
		# Add fake coordinates for missing data
		df <- df %>% 
			mutate(Population_Longitude = ifelse(is.na(Population_Longitude), -999, Population_Longitude),
						 Population_Latitude = ifelse(is.na(Population_Latitude), -999, Population_Latitude))
		
		# Retrieve country code
		country_code <- get_country_code(df)
		
		# Load in raster for country
		raster <- load_raster(country_code, city, data_in)
		
		# Create spatial point dataframe from latitude and longitude
		spdf <- SpatialPointsDataFrame(
			coords = df %>% 
				dplyr::select(Population_Longitude, Population_Latitude),
			proj4string = raster@crs,
			data = df
			)
		
		# Calculate GMIS data for population
		GMIS_data <- raster::extract(x = raster, y = spdf, method = "simple", buffer = buffer)
		GMIS_data <- ifelse(is.na(GMIS_data), 255, GMIS_data)  # Missing data needs to be 255
		
		# Take mean GMIS across all cells included within buffer
		GMIS_data_mod <- GMIS_data %>% 
			# Convert GMIS values of 200 to 0, as per documentation
			# Convert GMIS values of 255 to missing
			map(., function(x) case_when(x == 200 ~ 0,
																	 x == 255 ~ NA_real_,
																	 TRUE ~ x)) %>% 
			map(., mean, na.rm = TRUE) %>%  # Ignore cells with missing GMIS values when calculating mean
			unlist()
		
		# Add column with GMIS values
		df_out <- df %>% 
			mutate(GMIS_Mean = GMIS_data_mod,
						 GMIS_Mean = ifelse(GMIS_Mean == 255, NA, GMIS_Mean))
		
		# Add unique identifier to the data
		df_out$UID <- paste(df_out$City, df_out$Population, sep = ".")
		
		# Reorganize the data
		df_out <- df_out %>%
			dplyr::select(UID, Country, City, GMIS_Mean)
		
		write_csv(df_out, file = data_out, col_names = TRUE)
		
		}
	
	}
```




\newpage
### calculate_points_transects_GMIS

```{r calculate_points_transects_GMIS Function, echo = TRUE}
#' Description goes here...
#' 
#' 

## Set the function
calculate_points_transects_GMIS <- function(df, data_in, data_out, buffer = 250){
	
	# Get city name
	city <- df %>% pull(City) %>% unique()

	# Do not execute if file exists
	data_out <- paste0(data_out, city, "_GMIS.csv")
	if(file.exists(data_out)){
		print(sprintf("GMIS data already exists for %s", city))
		# Otherwise extract data
	}else{
		
		# Add fake coordinates for missing data
		df <- df %>% 
			mutate(Longitude = ifelse(is.na(Longitude), -999, Longitude),
						 Latitude = ifelse(is.na(Latitude), -999, Latitude))
		
		# Retrieve country code
		country_code <- get_country_code(df)
		
		# Load in raster for country
		raster <- load_raster(country_code, city, data_in)
		
		# Create spatial point dataframe from latitude and longitude
		spdf <- SpatialPointsDataFrame(
			coords = df %>% 
				dplyr::select(Longitude, Latitude),
			proj4string = raster@crs,
			data = df
			)
		
		# Calculate GMIS data for population
		GMIS_data <- raster::extract(x = raster, y = spdf, method = "simple", buffer = buffer)
		GMIS_data <- ifelse(is.na(GMIS_data), 255, GMIS_data)  # Missing data needs to be 255
		
		# Take mean GMIS across all cells included within buffer
		GMIS_data_mod <- GMIS_data %>% 
			# Convert GMIS values of 200 to 0, as per documentation
			# Convert GMIS values of 255 to missing
			map(., function(x) case_when(x == 200 ~ 0,
																	 x == 255 ~ NA_real_,
																	 TRUE ~ x)) %>% 
			map(., mean, na.rm = TRUE) %>%  # Ignore cells with missing GMIS values when calculating mean
			unlist()
		
		# Add column with GMIS values
		df_out <- df %>% 
			mutate(GMIS_Mean = GMIS_data_mod,
						 GMIS_Mean = ifelse(GMIS_Mean == 255, NA, GMIS_Mean))
		
		# Reorganize the data
		df_out <- df_out %>%
			dplyr::select(UID, Country, City, GMIS_Mean)
		
		write_csv(df_out, file = data_out, col_names = TRUE)
		
		}
	
	}
```




\newpage
# Calculate GMIS Data

```{r Calculate GMIS Data, echo = TRUE, results = "hide"}
## Set data_in for raw GMIS raster datasets
GMIS_rasters_path <- "raster_files/GMIS_rasters/"


## Set data_out for GMIS data
# GLUE transects
data_out_1 <- "data/GMIS_data/GLUE_transects_GMIS/"
# Random points
data_out_2 <- "data/GMIS_data/random_points_GMIS/"
# Systematic points
data_out_3 <- "data/GMIS_data/systematic_points_GMIS/"
# Random transects
data_out_4 <- "data/GMIS_data/random_transects_GMIS/"


## Calculate GMIS for each site across all sampling types
# GLUE transects
purrr::walk(
	GLUE.transects.df.list,
	calculate_GLUE_transect_GMIS,
	data_in = GMIS_rasters_path,
	data_out = data_out_1
	)
# Random points
purrr::walk(
	random.points.df.list,
	calculate_points_transects_GMIS,
	data_in = GMIS_rasters_path,
	data_out = data_out_2
	)
# Systematic points
purrr::walk(
	systematic.points.df.list,
	calculate_points_transects_GMIS,
	data_in = GMIS_rasters_path,
	data_out = data_out_3
	)
# Random transects
purrr::walk(
	random.transects.df.list,
	calculate_points_transects_GMIS,
	data_in = GMIS_rasters_path,
	data_out = data_out_4
	)
```




\newpage
# Workspace Information

```{r R Packages, echo = FALSE}
df_session_packages <- devtools::session_info()$packages %>% 
  as.data.frame(.) %>% 
  filter(attached == TRUE) %>% 
  dplyr::select(loadedversion, date) %>% 
  rownames_to_column

colnames(df_session_packages) <- c("Package", "Loaded Version", "Date")

kable(
  df_session_packages, 
  booktabs = TRUE,
  caption = "Packages required for data management and analyses."
  ) %>%
	kable_styling(
		full_width = FALSE,
  	latex_options = c("HOLD_position", "striped")
  	) 
```




