---
title: "GLUE-urbanQuant"
subtitle: "Impervious Surface Cover Data"
author: "David Murray-Stoker"
output:
  pdf_document:
    toc: true
    toc_depth: 4
    fig_caption: yes
    latex_engine: xelatex
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(results = "hold", fig.pos = "H", fig.align = "center", out.width = "92.5%")
options(knitr.graphics.error = FALSE)
kableExtra::usepackage_latex("float")
```

```{r Load Packages for R Markdown, include = FALSE}
library(kableExtra)
library(knitr)
```

```{r Load Packages & Data, include = FALSE}
## Load the tidyverse
library(tidyverse)

## Packages for data extraction and management
library(raster)
library(sp)
```







\newpage
# Load Data

```{r create_df_list Function, echo = TRUE}
#' Creates a list with dataframes as elements for all csv files in data_in
#'
#' @param data_in Path to directory containing csv files to load
#'
#' @return df_list List of dataframes, each from a different csv file

## Set the function
create_df_list <- function(data_in) {
  # Get all csv files in data_in
  files <- dir(data_in, pattern = "*.csv")

  # Read in all the files, appending the path before the filename
  df_list <- files %>%
    map(~ read_csv(file.path(data_in, .), show_col_types = FALSE))

  return(df_list)
}
```

\vspace{10pt}

```{r Create Lists of Dataframes, echo = TRUE}
## Load all GLUE transects as a list
GLUE.transect.data.path <- "data/data_filtered/"
GLUE.transect.df.list <- create_df_list(GLUE.transect.data.path)

## Load all random transects as a list
random.transect.data.path <- "data/filtered_random_transects/"
random.transect.df.list <- create_df_list(random.transect.data.path)

## Load all random points as a list
random.points.data.path <- "data/filtered_random_points/"
random.points.df.list <- create_df_list(random.points.data.path)

## Load all systematic points as a list
systematic.points.data.path <- "data/filtered_systematic_points/"
systematic.points.df.list <- create_df_list(systematic.points.data.path)
```







\newpage
# Impervious Surface Cover Data

Description goes here...





\newpage
## get_country_code Function

```{r get_country_code Function, echo = TRUE}
#' Function that converts a country name to the correct code for loading the
#' associated ISC raster. Function is nested within the `load_raster` function.
#'
#' @param df Dataframe with the country for each respective city
#'
#' @return country_code Code associated the ISC tif file for that country

## Set the function
get_country_code <- function(df) {
  # Get country
  country <- df %>%
    pull(Country) %>%
    unique()

  # Convert country to country code
  country_code <- case_when(
    country == "Argentina" ~ "ARG",
    country == "Australia" ~ "AUS",
    country == "Belgium" ~ "BEL",
    country == "Brazil" ~ "BRA",
    country == "Canada" ~ "CAN",
    country == "Chile" ~ "CHL",
    country == "China" ~ "CHN",
    country == "Colombia" ~ "COL",
    country == "Ecuador" ~ "ECU",
    country == "Finland" ~ "FIN",
    country == "France" ~ "FRA",
    country == "Germany" ~ "DEU",
    country == "Greece" ~ "GRC",
    country == "Iran" ~ "IRN",
    country == "Japan" ~ "JPN",
    country == "Mexico" ~ "MEX",
    country == "Netherlands" ~ "NLD",
    country == "Norway" ~ "NOR",
    country == "New Zealand" ~ "NZL",
    country == "Poland" ~ "POL",
    country == "Portugal" ~ "PRT",
    country == "Sweden" ~ "SWE",
    country == "Switzerland" ~ "CHE",
    country == "UK" ~ "GBR",
    country == "USA" ~ "USA",
    country == "South Africa" ~ "ZAF",
    TRUE ~ "NA"
  )

  return(country_code)
}
```





\newpage
## load_raster Function

```{r load_raster Function, echo = TRUE}
#' Loads the ISC raster tif file associated with a given city and country.
#' Function is nested within the `calculate_GLUE_transect_ISC` and 
#' `calculate_points_transect_ISC` functions.
#'
#' @param country_code Code associated the ISC tif file for that country,
#'   returned from the country_code function
#' @param city Name of the city for which the ISC tif file should be loaded
#' @raster_path Directory for the folder containing all ISC rasters in tif files
#'
#' @return raster.file Loads the ISC raster file for a given city and country

## Set the function
load_raster <- function(country_code, city, raster_path) {
  # Regex pattern to match country"s raster
  # Handles a few edge cases for countries with multiple rasters
  if (country_code == "USA" & !(city %in% c("Fairbanks", "Anchorage"))) {
    pattern <- "^USAw1_.*.tif$"
  } else if (country_code == "USA" & city %in% c("Fairbanks", "Anchorage")) {
    pattern <- "^USAW3_.*.tif$"
  } else if (country_code == "NZL") {
    pattern <- "^NZLe_.*.tif$"
  } else {
    pattern <- sprintf("^%s_.*.tif$", country_code)
  }

  # Path to raster
  raster_file <- list.files(raster_path, pattern = pattern, recursive = TRUE)
  raster_path <- paste0(raster_path, raster_file)

  # Load and return raster file
  raster.file <- raster::raster(raster_path)

  return(raster.file)
}
```





\newpage
## calculate_GLUE_transect_ISC Function

```{r calculate_GLUE_transect_ISC Function, echo = TRUE}
#' Calculates mean ISC within a 250-m radius of a site along a GLUE transect.
#' Data are exported as a csv file.
#'
#' @param df Dataframe with city and country identifiers and lat/long coordinates
#'   for each site. Coordinates must be in decimal degrees. Separate df for
#'   each city.
#' @param raster_path Directory to the ISC raster file in tif format.
#' @param data_out Directory to export csv files with mean ISC data.
#' @param site_buffer Radius around each site in which mean ISC will be calculated;
#'   radius is in m.
#'
#' @return raster.file Loads the ISC raster file for a given city and country.

## Set the function
calculate_GLUE_transect_ISC <- function(df, raster_path, data_out, site_buffer = 250) {
  # Get city name
  city <- df %>%
    pull(City) %>%
    unique()

  # Do not execute if file exists
  data_out <- paste0(data_out, city, "_ISC.csv")

  # Add fake coordinates for missing data
  df <- df %>%
    mutate(
      Site_Longitude = ifelse(is.na(Site_Longitude), -999, Site_Longitude),
      Site_Latitude = ifelse(is.na(Site_Latitude), -999, Site_Latitude)
    )

  # Retrieve country code
  country_code <- get_country_code(df)

  # Load in raster for country
  raster.file <- load_raster(country_code, city, raster_path)

  # Create spatial point dataframe from latitude and longitude
  spdf <- sp::SpatialPointsDataFrame(
    coords = df %>%
      dplyr::select(Site_Longitude, Site_Latitude),
    proj4string = raster.file@crs,
    data = df
  )

  # Calculate ISC data for each population
  ISC_data <- raster::extract(
    x = raster.file,
    y = spdf,
    method = "simple",
    buffer = site_buffer
  )
  ISC_data <- ifelse(is.na(ISC_data), 255, ISC_data) # Missing data needs to be 255

  # Take mean ISC across all cells included within buffer
  ISC_data_mod <- ISC_data %>%
    # Convert ISC values of 200 to 0, as per documentation
    # Convert ISC values of 255 to missing
    map(., function(x) {
      case_when(
        x == 200 ~ 0,
        x == 255 ~ NA_real_,
        TRUE ~ x
      )
    }) %>%
    map(., mean, na.rm = TRUE) %>% # Ignore cells with missing ISC values when calculating mean
    unlist()

  # Add column with ISC values
  df_out <- df %>%
    mutate(
      ISC_Mean = ISC_data_mod,
      ISC_Mean = ifelse(ISC_Mean == 255, NA, ISC_Mean)
    )

  # Add unique identifier to the data
  df_out$UID <- paste(df_out$City, rownames(df_out), sep = ".")

  # Reorganize the data
  df_out <- df_out %>%
    dplyr::select(UID, Country, City, ISC_Mean)

  write_csv(df_out, file = data_out, col_names = TRUE)
}
```





\newpage
## calculate_points_transect_ISC Function

```{r calculate_points_transect_ISC Function, echo = TRUE}
#' Calculates mean ISC within a 250-m radius of a site  based on the random
#' transect, random points, or systematic points sampling designs. Data are 
#' exported as a csv file.
#'
#' @param df Dataframe with city and country identifiers and lat/long coordinates
#'   for each site. Coordinates must be in decimal degrees. Separate df for
#'   each city.
#' @param raster_path Directory to the ISC raster file in tif format.
#' @param data_out Directory to export csv files with mean ISC data.
#' @param site_buffer Radius around each site in which mean ISC will be calculated;
#'   radius is in m.
#'
#' @return raster.file Loads the ISC raster file for a given city and country.

## Set the function
calculate_points_transect_ISC <- function(df, raster_path, data_out, site_buffer = 250) {
  # Get city name
  city <- df %>%
    pull(City) %>%
    unique()

  # Do not execute if file exists
  data_out <- paste0(data_out, city, "_ISC.csv")

  # Add fake coordinates for missing data
  df <- df %>%
    mutate(
      Longitude = ifelse(is.na(Longitude), -999, Longitude),
      Latitude = ifelse(is.na(Latitude), -999, Latitude)
    )

  # Retrieve country code
  country_code <- get_country_code(df)

  # Load in raster for country
  raster.file <- load_raster(country_code, city, raster_path)

  # Create spatial point dataframe from latitude and longitude
  spdf <- sp::SpatialPointsDataFrame(
    coords = df %>%
      dplyr::select(Longitude, Latitude),
    proj4string = raster.file@crs,
    data = df
  )

  # Calculate ISC data for each population
  ISC_data <- raster::extract(
    x = raster.file,
    y = spdf,
    method = "simple",
    buffer = site_buffer
  )
  ISC_data <- ifelse(is.na(ISC_data), 255, ISC_data) # Missing data needs to be 255

  # Take mean ISC across all cells included within buffer
  ISC_data_mod <- ISC_data %>%
    # Convert ISC values of 200 to 0, as per documentation
    # Convert ISC values of 255 to missing
    map(., function(x) {
      case_when(
        x == 200 ~ 0,
        x == 255 ~ NA_real_,
        TRUE ~ x
      )
    }) %>%
    map(., mean, na.rm = TRUE) %>% # Ignore cells with missing ISC values when calculating mean
    unlist()

  # Add column with ISC values
  df_out <- df %>%
    mutate(
      ISC_Mean = ISC_data_mod,
      ISC_Mean = ifelse(ISC_Mean == 255, NA, ISC_Mean)
    )

  # Add unique identifier to the data
  df_out$UID <- paste(df_out$City, rownames(df_out), sep = ".")

  # Reorganize the data
  df_out <- df_out %>%
    dplyr::select(UID, Country, City, ISC_Mean)

  write_csv(df_out, file = data_out, col_names = TRUE)
}
```







\newpage
# Calculate ISC Data

```{r Calculate ISC Data, echo = TRUE, results = "hide"}
## Set raster_path for ISC raster datasets
ISC_rasters_path <- "raster_files/ISC_rasters/"


## Set data_out for ISC data
# GLUE transects
data_out_1 <- "data/ISC_data/GLUE_transects_ISC/"
# Random transects
data_out_2 <- "data/ISC_data/random_transects_ISC/"
# Random points
data_out_3 <- "data/ISC_data/random_points_ISC/"
# Systematic points
data_out_4 <- "data/ISC_data/systematic_points_ISC/"


## Calculate ISC for each site across all sampling types
# GLUE transect
purrr::walk(
  GLUE.transect.df.list,
  calculate_GLUE_transect_ISC,
  raster_path = ISC_rasters_path,
  data_out = data_out_1
)
# Random transect
purrr::walk(
  random.transect.df.list,
  calculate_points_transect_ISC,
  raster_path = ISC_rasters_path,
  data_out = data_out_2
)
# Random points
purrr::walk(
  random.points.df.list,
  calculate_points_transect_ISC,
  raster_path = ISC_rasters_path,
  data_out = data_out_3
)
# Systematic points
purrr::walk(
  systematic.points.df.list,
  calculate_points_transect_ISC,
  raster_path = ISC_rasters_path,
  data_out = data_out_4
)
```







\newpage
# Workspace Information

```{r R Packages, echo = FALSE}
df_session_packages <- devtools::session_info()$packages %>%
  as.data.frame(.) %>%
  filter(attached == TRUE) %>%
  dplyr::select(loadedversion, date) %>%
  rownames_to_column()

colnames(df_session_packages) <- c("Package", "Loaded Version", "Date")

kable(
  df_session_packages,
  booktabs = TRUE,
  caption = "Packages required for data management and analyses."
) %>%
  kable_styling(
    full_width = FALSE,
    latex_options = c("HOLD_position", "striped")
  )
```
