---
title: "GLUE-urbanQuant"
subtitle: "WorldClim Data"
author: "David Murray-Stoker"
output:
  pdf_document:
    toc: true
    toc_depth: 4
    fig_caption: yes
    latex_engine: xelatex
always_allow_html: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(results = "hold", fig.pos = "H", fig.align = "center", out.width = "92.5%")
options(knitr.graphics.error = FALSE)
kableExtra::usepackage_latex("float")
```

```{r Load Packages for R Markdown, include = FALSE}
library(kableExtra)
library(knitr)
```

```{r Load Packages & Data, include = FALSE}
## Load the tidyverse
library(tidyverse)

## Packages for data extraction and management
library(raster)
```







\newpage
# Load Data

```{r create_df_list Function, echo = TRUE}
#' Creates a list with dataframes as elements for all csv files in data_in
#'
#' @param data_in Path to directory containing csv files to load
#'
#' @return df_list List of dataframes, each from a different csv file

## Set the function
create_df_list <- function(data_in) {
  # Get all csv files in data_in
  files <- dir(data_in, pattern = "*.csv")

  # Read in all the files, appending the path before the filename
  df_list <- files %>%
    map(~ read_csv(file.path(data_in, .), show_col_types = FALSE))

  return(df_list)
}
```

\vspace{10pt}

```{r Create Lists of Dataframes, echo = TRUE}
## Load all GLUE transects as a list
GLUE.transect.data.path <- "data/data_filtered/"
GLUE.transect.df.list <- create_df_list(GLUE.transect.data.path)

## Load all random transects as a list
random.transect.data.path <- "data/filtered_random_transects/"
random.transect.df.list <- create_df_list(random.transect.data.path)

## Load all random points as a list
random.points.data.path <- "data/filtered_random_points/"
random.points.df.list <- create_df_list(random.points.data.path)

## Load all systematic points as a list
systematic.points.data.path <- "data/filtered_systematic_points/"
systematic.points.df.list <- create_df_list(systematic.points.data.path)
```







\newpage
# WorldClim Data

Description goes here...





\newpage
## calculate_GLUE_transect_WorldClim Function

```{r calculate_GLUE_transect_WorldClim Function, echo = TRUE}
#' Calculates WorldClim variables (mean annual temperature, temperature seasonality
#' range annual temperature, annual precipitation, and precipitation seasonality)
#' for each site along a GLUE transect. WorldClim variables are calculated at
#' 1-km resolution for each site. Data for each of the 5 WorldClim variables
#' are exported as a csv file.
#'
#' @param df Dataframe with city and country identifiers and lat/long coordinates
#'   for each site. Coordinates must be in decimal degrees. Separate df for
#'   each city.
#' @param data_out Directory to export csv files with WorldClim data.

## Set the function
calculate_GLUE_transect_WorldClim <- function(df, data_out) {
  # Get city name
  city <- df %>%
    pull(City) %>%
    unique()

  # Get country name
  country <- df %>%
    pull(Country) %>%
    unique()

  # Path for exporting WorldClim data
  data_out <- paste0(data_out, city, "_WorldClim.csv")

  # Add fake coordinates for missing data
  df <- df %>%
    mutate(
      Site_Longitude = ifelse(is.na(Site_Longitude), -999, Site_Longitude),
      Site_Latitude = ifelse(is.na(Site_Latitude), -999, Site_Latitude)
    )

  ## Mean Annual Temperature-----------------------------------------------
  # Load the raster
  raster_1 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_1.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_1 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Site_Longitude, Site_Latitude),
    proj4string = raster_1@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Mean_Annual_Temperature_data <- raster::extract(x = raster_1, y = spdf_1, method = "simple")

  ## Temperature Seasonality-----------------------------------------------
  # Load the raster
  raster_2 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_4.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_2 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Site_Longitude, Site_Latitude),
    proj4string = raster_2@crs,
    data = df
  )

  # Calculate temperature seasonality for each population
  Temperature_Seasonality_data <- raster::extract(x = raster_2, y = spdf_2, method = "simple")

  ## Range Annual Temperature----------------------------------------------
  # Load the raster
  raster_3 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_7.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_3 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Site_Longitude, Site_Latitude),
    proj4string = raster_3@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Range_Annual_Temperature_data <- raster::extract(x = raster_3, y = spdf_3, method = "simple")

  ## Annual Precipitation--------------------------------------------------
  # Load the raster
  raster_4 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_12.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_4 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Site_Longitude, Site_Latitude),
    proj4string = raster_4@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Annual_Precipitation_data <- raster::extract(x = raster_4, y = spdf_4, method = "simple")

  ## Precipitation Seasonality---------------------------------------------
  # Load the raster
  raster_5 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_15.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_5 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Site_Longitude, Site_Latitude),
    proj4string = raster_5@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Precipitation_Seasonality_data <- raster::extract(x = raster_5, y = spdf_5, method = "simple")

  ## Data Management-------------------------------------------------------

  ## Tibble of extracted WorldClim data
  WorldClim_data <- tibble(
    UID = paste(df$City, rownames(df), sep = "."),
    Country = country,
    City = city,
    Mean_Annual_Temperature = Mean_Annual_Temperature_data,
    Temperature_Seasonality = Temperature_Seasonality_data / 100,
    Range_Annual_Temperature = Range_Annual_Temperature_data,
    Annual_Precipitation = Annual_Precipitation_data,
    Precipitation_Seasonality = Precipitation_Seasonality_data
  )

  write_csv(WorldClim_data, file = data_out, col_names = TRUE)
}
```





\newpage
## calculate_points_transect_WorldClim Function

```{r calculate_points_transect_WorldClim Function, echo = TRUE}
#' Calculates WorldClim variables (mean annual temperature, temperature seasonality
#' range annual temperature, annual precipitation, and precipitation seasonality)
#' based on the random transect, random points, or systematic points sampling
#' designs. WorldClim variables are calculated at 1-km resolution for each site.
#' Data for each of the 5 WorldClim variables are exported as a csv file.
#'
#' @param df Dataframe with city and country identifiers and lat/long coordinates
#'   for each site. Coordinates must be in decimal degrees. Separate df for
#'   each city.
#' @param data_out Directory to export csv files with WorldClim data.

## Set the function
calculate_points_transect_WorldClim <- function(df, data_out) {
  # Get city name
  city <- df %>%
    pull(City) %>%
    unique()

  # Get country name
  country <- df %>%
    pull(Country) %>%
    unique()

  # Path for exporting WorldClim data
  data_out <- paste0(data_out, city, "_WorldClim.csv")

  # Add fake coordinates for missing data
  df <- df %>%
    mutate(
      Longitude = ifelse(is.na(Longitude), -999, Longitude),
      Latitude = ifelse(is.na(Latitude), -999, Latitude)
    )

  ## Mean Annual Temperature-----------------------------------------------
  # Load the raster
  raster_1 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_1.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_1 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Longitude, Latitude),
    proj4string = raster_1@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Mean_Annual_Temperature_data <- raster::extract(x = raster_1, y = spdf_1, method = "simple")

  ## Temperature Seasonality-----------------------------------------------
  # Load the raster
  raster_2 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_4.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_2 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Longitude, Latitude),
    proj4string = raster_2@crs,
    data = df
  )

  # Calculate temperature seasonality for each population
  Temperature_Seasonality_data <- raster::extract(x = raster_2, y = spdf_2, method = "simple")

  ## Range Annual Temperature----------------------------------------------
  # Load the raster
  raster_3 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_7.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_3 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Longitude, Latitude),
    proj4string = raster_3@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Range_Annual_Temperature_data <- raster::extract(x = raster_3, y = spdf_3, method = "simple")

  ## Annual Precipitation--------------------------------------------------
  # Load the raster
  raster_4 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_12.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_4 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Longitude, Latitude),
    proj4string = raster_4@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Annual_Precipitation_data <- raster::extract(x = raster_4, y = spdf_4, method = "simple")

  ## Precipitation Seasonality---------------------------------------------
  # Load the raster
  raster_5 <- raster::raster("raster_files/WorldClim_2.1_rasters/wc2.1_30s_bio_15.tif")

  # Create spatial point dataframe from latitude and longitude
  spdf_5 <- SpatialPointsDataFrame(
    coords = df %>% dplyr::select(Longitude, Latitude),
    proj4string = raster_5@crs,
    data = df
  )

  # Calculate mean annual temperature for each population
  Precipitation_Seasonality_data <- raster::extract(x = raster_5, y = spdf_5, method = "simple")

  ## Data Management-------------------------------------------------------

  ## Tibble of extracted WorldClim data
  WorldClim_data <- tibble(
    UID = df$UID,
    Country = country,
    City = city,
    Mean_Annual_Temperature = Mean_Annual_Temperature_data,
    Temperature_Seasonality = Temperature_Seasonality_data / 100,
    Range_Annual_Temperature = Range_Annual_Temperature_data,
    Annual_Precipitation = Annual_Precipitation_data,
    Precipitation_Seasonality = Precipitation_Seasonality_data
  )

  write_csv(WorldClim_data, file = data_out, col_names = TRUE)
}
```







\newpage
# Calculate WorldClim Data

```{r Calculate WorldClim Data, echo = TRUE, results = "hide"}
## Set data_out for WorldClim values for the points and transects
# GLUE transect
data_out_1 <- "data/WorldClim_data/GLUE_transects_WorldClim/"
# Random transect
data_out_2 <- "data/WorldClim_data/random_transects_WorldClim/"
# Random points
data_out_3 <- "data/WorldClim_data/random_points_WorldClim/"
# Systematic points
data_out_4 <- "data/WorldClim_data/systematic_points_WorldClim/"


## Calculate WorldClim data for each site across all sampling types
# GLUE transects
purrr::walk(
  GLUE.transects.df.list,
  calculate_GLUE_transect_WorldClim,
  data_out = data_out_1
)
# Random transects
purrr::walk(
  random.transects.df.list,
  calculate_points_transect_WorldClim,
  data_out = data_out_2
)
# Random points
purrr::walk(
  random.points.df.list,
  calculate_points_transect_WorldClim,
  data_out = data_out_3
)
# Systematic points
purrr::walk(
  systematic.points.df.list,
  calculate_points_transect_WorldClim,
  data_out = data_out_4
)
```







\newpage
# Workspace Information

```{r R Packages, echo = FALSE}
df_session_packages <- devtools::session_info()$packages %>%
  as.data.frame(.) %>%
  filter(attached == TRUE) %>%
  dplyr::select(loadedversion, date) %>%
  rownames_to_column()

colnames(df_session_packages) <- c("Package", "Loaded Version", "Date")

kable(
  df_session_packages,
  booktabs = TRUE,
  caption = "Packages required for data management and analyses."
) %>%
  kable_styling(
    full_width = FALSE,
    latex_options = c("HOLD_position", "striped")
  )
```
